data_path: ./   # 数据存放路径

# 匹配
registration_method: CERESSE3ICP   # 选择点云匹配方法，目前支持：NDT ICP, OPTICP,CERESQTICP,CERESSE3ICP

# 局部地图
key_frame_distance: 2.0 # 关键帧距离
local_frame_num: 20
local_map_filter: voxel_filter # 选择滑窗地图点云滤波方法，目前支持：voxel_filter

# rviz显示
display_filter: voxel_filter # rviz 实时显示点云时滤波方法，目前支持：voxel_filter

# 当前帧
frame_filter: voxel_filter # 选择当前帧点云滤波方法，目前支持：voxel_filter

# 各配置选项对应参数
# 匹配相关参数
NDT:
    res : 1.0
    step_size : 0.1
    trans_eps : 0.01
    max_iter : 30

ICP:
    max_corres_dist : 0.9 # 最近点组合之间的最大距离，这里需要比local_map中的leaf_size的树值大，否则很难找到对应的点
    trans_eps : 0.01
    euclidean_fitness_eps : 0.01 
    max_iter : 300

## 滤波相关参数
voxel_filter:
    local_map:
        leaf_size: [0.6, 0.6, 0.6]
    frame:
        leaf_size: [1.3, 1.3, 1.3]
    display:
        leaf_size: [0.5, 0.5, 0.5]